name: Update README stats

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à 00:00 UTC
  workflow_dispatch:   # permite rodar manualmente

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node --version
          node update-readme.js

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README stats" || echo "No changes to commit"
          git push
